package com.pv207.pv207_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Bug implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BUG_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "BUG_ID_SEQ", name = "BUG_ID_GENERATOR")
	@org.kie.api.definition.type.Label("ID")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label("DEV_notes")
	private java.lang.String dev_notes;

	@org.kie.api.definition.type.Label("Assignee")
	private java.lang.String assignee;

	@org.kie.api.definition.type.Label("Issue reported")
	private java.lang.String from_issue;

	public Bug() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getDev_notes() {
		return this.dev_notes;
	}

	public void setDev_notes(java.lang.String dev_notes) {
		this.dev_notes = dev_notes;
	}

	public java.lang.String getAssignee() {
		return this.assignee;
	}

	public void setAssignee(java.lang.String assignee) {
		this.assignee = assignee;
	}

	public java.lang.String getFrom_issue() {
		return this.from_issue;
	}

	public void setFrom_issue(java.lang.String from_issue) {
		this.from_issue = from_issue;
	}

	public Bug(java.lang.Long id, java.lang.String name,
			java.lang.String description, java.lang.String dev_notes,
			java.lang.String assignee, java.lang.String from_issue) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.dev_notes = dev_notes;
		this.assignee = assignee;
		this.from_issue = from_issue;
	}

}