package com.pv207.pv207_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Feedback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("stars")
	private java.lang.Integer stars;
	@org.kie.api.definition.type.Label("review")
	private java.lang.String review;

	public Feedback() {
	}

	public java.lang.Integer getStars() {
		return this.stars;
	}

	public void setStars(java.lang.Integer stars) {
		this.stars = stars;
	}

	public java.lang.String getReview() {
		return this.review;
	}

	public void setReview(java.lang.String review) {
		this.review = review;
	}

	public Feedback(java.lang.Integer stars, java.lang.String review) {
		this.stars = stars;
		this.review = review;
	}

}