package com.pv207.pv207_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Date")
	private java.util.Date date;

	@org.kie.api.definition.type.Label(value = "Reporter_email")
	private java.lang.String reporter_email;

	public Issue() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.lang.String getReporter_email() {
		return this.reporter_email;
	}

	public void setReporter_email(java.lang.String reporter_email) {
		this.reporter_email = reporter_email;
	}

	public Issue(java.lang.String name, java.lang.String description,
			java.util.Date date, java.lang.String reporter_email) {
		this.name = name;
		this.description = description;
		this.date = date;
		this.reporter_email = reporter_email;
	}

}